# Generated by Django 6.0.5 on 2026-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
