# Generated by Django 6.0.5 on 2026-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_meneger',
            field=models.BooleanField(default=False),
        ),
    ]
