# Generated by Django 6.0.5 on 2026-06-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_meneger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_meneger',
            new_name='is_manager',
        ),
    ]
