# Generated by Django 6.0.5 on 2026-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_courierlocation_deliverychat_deliverychatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
