# Generated by Django 6.0.5 on 2026-06-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
